# Mixed Topological Loss Configuration

# Primary loss (used from the beginning)
primary_loss:
  path: "losses.chamfer_class"
  class: "ChamferBoundarySDFLoss"
  params:
    weight_sdf:      0.0     # multiplier inside make_dSDF
    weight_chamfer:  1.0      # max pairing distance in pixels
    update_scale:    1.0      # weight of the L1 term
    dist_threshold:  3
  # path: "losses.weighted_mse"
  # class: "WeightedMSELoss"
  # params:
  #   road_weight: 4
  #   bg_weight: 1
  #   threshold: 0
  #   greater_is_road: False
  #   reduction: mean

  # class: "MSELoss"  # Built-in PyTorch loss
  # params: {}

# # Secondary loss (activated after start_epoch)
# secondary_loss:
#   path: "losses.chamfer_class"  # Path to the module containing the loss
#   class: "ChamferBoundarySDFLoss"  # Name of the loss class
#   params:
#     update_scale: 1.0     # scale applied to the gradient projection
#     dist_threshold: 3.0   # max distance (in pixels) to consider a match
#     chamfer_weight: 1.0         # weight for the “inject” term
#     pixel_weight: 1.0          # weight for the “pixel” term

## Mixing parameters
alpha: 1  # Weight for the secondary loss 
start_epoch: 0  # Epoch to start using the secondary loss



 