# Mixed Topological Loss Configuration

# Primary loss (used from the beginning)
primary_loss:
  path: "losses.fixed_lif_weighted_mse"
  class: "FixedLUTWeightedMSELoss"
  params:
    sdf_min: 0
    sdf_max: 15.0
    n_bins: 15
    reduction: "mean"
    lut_path: "weights/al175_15_lif_weights.pt"

  # path: "losses.weighted_mse"
  # class: "WeightedMSELoss"
  # params:
  #   road_weight: 4
  #   bg_weight: 1
  #   threshold: 0
  #   greater_is_road: False
  #   reduction: mean

  # class: "MSELoss"  # Built-in PyTorch loss
  # params: {}

# # Secondary loss (activated after start_epoch)
secondary_loss:
  path: "losses.cape.loss"  # Path to the module containing the loss
  class: "CAPE"  # Name of the loss class
  params:
    window_size: 48
    three_dimensional: true
    distance_threshold: 15.0
    dilation_radius: 10.0 
    single_edge: true

# # Mixing parameters
alpha: 0.5  # Weight for the secondary loss (0 to 1)
start_epoch: 5000  # Epoch to start using the secondary loss
