# Mixed Topological Loss Configuration

# Primary loss (used from the beginning)
primary_loss:
  path: "losses.fixed_lif_weighted_mse"
  class: "FixedLUTWeightedMSELoss"
  params:
    sdf_min: -7
    sdf_max: 7.0
    n_bins: 15
    reduction: "mean"
    lut_path: "weights/mass_7_lif_weights.pt"

  # path: "losses.weighted_mse"
  # class: "WeightedMSELoss"
  # params:
  #   road_weight: 4
  #   bg_weight: 1
  #   threshold: 0
  #   greater_is_road: False
  #   reduction: mean

  # class: "MSELoss"  # Built-in PyTorch loss
  # params: {}

# # Secondary loss (activated after start_epoch)
secondary_loss:
  path: "losses.chamfer_class"
  class: "ChamferBoundarySDFLoss"
  params:
    pixel_weight:      1.0      # weight of the L1 term
    chamfer_weight:    1.0      # overall scale of the injected gradient
    update_scale:      10.0     # multiplier inside make_dSDF
    dist_threshold:    2.0      # max pairing distance in pixels
    max_points:        2048     # subsample number of zero‐crossings
    normalize_normals: false    # whether to re‐normalize normals in dSDF
    use_hook:          true     # register the backward hook
    clip_sdf_to:       null     # no clipping of raw SDF values
    clip_dSDF:         null     # no clipping of the injected gradient

## Mixing parameters
alpha: 1  # Weight for the secondary loss 
start_epoch: 0  # Epoch to start using the secondary loss



 