# Mixed Topological Loss Configuration

# Primary loss (used from the beginning)
primary_loss:
  path: "losses.lif_weighted_mse"
  class: "LIFWeightedMSELoss"
  params:
    sdf_min: -7.0
    sdf_max: 7.0
    n_bins: 256
    eps: 0.02
    freeze_after_first: False
    reduction: "mean"

  # class: "WeightedMSELoss"
  # params:
  #   road_weight: 4
  #   bg_weight: 1
  #   threshold: 0
  #   greater_is_road: False
  #   reduction: mean

  # class: "MSELoss"  # Built-in PyTorch loss
  # params: {}

# # Secondary loss (activated after start_epoch)
secondary_loss:
  path: "losses.chamfer_class"  # Path to the module containing the loss
  class: "ChamferBoundarySDFLoss"  # Name of the loss class
  params:
    update_scale: 1.0
    dist_threshold: 3.0
    w_inject: 1.0
    w_pixel: 1.0

# # Mixing parameters
alpha: 1  # Weight for the secondary loss (0 to 1)
start_epoch: 10000  # Epoch to start using the secondary loss



 