name: dl
channels:
  - pytorch
  - esri
  - anaconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=2.1.0
  - affine=2.4.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - alabaster=0.7.16
  - alsa-lib=1.2.8
  - aom=3.5.0
  - archspec=0.2.3
  - asttokens=3.0.0
  - async-timeout=5.0.1
  - attr=2.5.1
  - attrs=24.3.0
  - babel=2.17.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blessed=1.21.0
  - blinker=1.9.0
  - blosc=1.21.5
  - boltons=24.1.0
  - boost-cpp=1.78.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.4.26
  - cachetools=5.5.1
  - cairo=1.16.0
  - certifi=2025.4.26
  - cffi=1.17.1
  - cfitsio=4.2.0
  - cgal-cpp=5.6
  - chardet=4.0.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=3.0.0
  - cmake=3.31.2
  - colorama=0.4.6
  - comm=0.2.1
  - conda=24.11.3
  - conda-build=25.3.2
  - conda-index=0.5.0
  - conda-libmamba-solver=24.9.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - contourpy=1.2.1
  - cryptography=44.0.1
  - cuda-cccl_linux-64=12.4.127
  - cuda-cudart=12.4.127
  - cuda-cudart-dev_linux-64=12.4.127
  - cuda-cudart-static_linux-64=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - cupy=13.4.1
  - cupy-core=13.4.1
  - curl=8.12.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - cytoolz=1.0.1
  - dash=3.0.4
  - dask-core=2024.5.0
  - dbus=1.13.18
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - distro=1.9.0
  - docutils=0.21.2
  - eigen=3.4.0
  - einops=0.7.0
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.6.4
  - fastrlock=0.8.3
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - filelock=3.13.1
  - flask=3.1.0
  - flexcache=0.3
  - flexparser=0.4
  - fmt=9.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.55.3
  - freeglut=3.2.2
  - freetype=2.13.3
  - freexl=1.0.6
  - frozendict=2.4.2
  - frozenlist=1.5.0
  - gdal=3.6.2
  - geos=3.11.1
  - geotiff=1.7.1
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - giflib=5.2.2
  - glib=2.78.1
  - glib-tools=2.78.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.9
  - google-auth=2.38.0
  - google-auth-oauthlib=0.4.4
  - gpustat=1.1.1
  - graphite2=1.3.14
  - grpcio=1.46.3
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.41
  - gudhi=3.8.0
  - harfbuzz=6.0.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - hilbertcurve=2.0.5
  - hopcroftkarp=1.2.4
  - icu=70.1
  - idna=3.7
  - imagecodecs-lite=2019.12.3
  - imageio=2.37.0
  - imagesize=1.4.1
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.0
  - iniconfig=1.1.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.15.0
  - ipywidgets=8.1.7
  - itsdangerous=2.2.0
  - jack=1.9.22
  - jasper=2.0.33
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - json-c=0.16
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_widgets=3.0.15
  - kealib=1.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libaec=1.1.3
  - libarchive=3.6.2
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libblas=3.9.0
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcups=2.3.3
  - libcurand=10.3.5.147
  - libcurl=8.12.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdb=6.2.32
  - libdeflate=1.17
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.6.4
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt=1.11.0
  - libgcrypt-devel=1.11.0
  - libgcrypt-lib=1.11.0
  - libgcrypt-tools=1.11.0
  - libgdal=3.6.2
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran-ng=8.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.1
  - libglu=9.0.0
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libiconv=1.18
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblief=0.12.3
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnetcdf=4.9.1
  - libnghttp2=1.57.0
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libogg=1.3.5
  - libopencv=4.7.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=15.2
  - libprotobuf=3.21.12
  - librttopo=1.1.0
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsolv=0.7.29
  - libspatialite=5.0.1
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=252
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libuv=1.48.0
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzip=1.10.1
  - libzlib=1.2.13
  - lightning-utilities=0.11.9
  - llvm-openmp=14.0.6
  - llvmlite=0.42.0
  - locket=1.0.0
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - menuinst=2.2.0
  - mistune=3.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - more-itertools=10.3.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - multidict=6.1.0
  - mysql=5.7.24
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - narwhals=1.31.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.2.1
  - ninja=1.12.1
  - nspr=4.35
  - nss=3.89.1
  - numba=0.59.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - nvidia-ml-py=12.575.51
  - oauthlib=3.2.2
  - ocl-icd=2.3.2
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.1.8
  - p11-kit=0.24.1
  - packaging=24.2
  - pandas=2.2.3
  - pandoc=3.7.0.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - partd=1.4.2
  - patch=2.7.6
  - patchelf=0.17.2
  - patsy=1.0.1
  - pcre2=10.40
  - persim=0.3.8
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pint=0.24.4
  - pip=25.0
  - pixman=0.40.0
  - pkginfo=1.12.0
  - platformdirs=3.10.0
  - plotly=6.1.0
  - pluggy=1.5.0
  - ply=3.11
  - poppler=23.03.0
  - poppler-data=0.4.12
  - postgresql=15.2
  - proj=9.1.1
  - prompt-toolkit=3.0.43
  - propcache=0.3.1
  - protobuf=4.21.12
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pure_eval=0.2.2
  - py-lief=0.12.3
  - py-opencv=4.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11=2.13.6
  - pybind11-abi=4
  - pybind11-global=2.13.6
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.15.1
  - pyjwt=2.10.1
  - pyopenssl=25.0.0
  - pyparsing=3.2.0
  - pyprism=1.0.3
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - pytest=8.2.1
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.1
  - python-libarchive-c=5.1
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-lightning=2.5.1
  - pytorch-mutex=1.0
  - pytorch_geometric=2.6.1
  - pytz=2024.1
  - pywavelets=1.5.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.8
  - rasterio=1.3.6
  - readline=8.2
  - referencing=0.30.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - retrying=1.3.3
  - rhash=1.4.3
  - ripser=0.6.12
  - rpds-py=0.22.3
  - rsa=4.7.2
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - scikit-build=0.18.1
  - scikit-image=0.19.3
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.8.0
  - shapely=2.0.1
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.1
  - snowballstemmer=2.2.0
  - snuggs=1.4.7
  - soupsieve=2.5
  - sphinx=7.3.7
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlite=3.45.3
  - stack_data=0.2.0
  - statsmodels=0.14.4
  - svt-av1=1.4.1
  - tbb=2021.8.0
  - tensorboard=2.11.2
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorboardx=2.6.2.2
  - threadpoolctl=3.5.0
  - tifffile=2020.6.3
  - tiledb=2.13.2
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.0.1
  - toolz=1.0.0
  - torchmetrics=1.4.0.post0
  - torchtriton=3.1.0
  - torchvision=0.15.2
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzcode=2025b
  - tzdata=2025a
  - unicodedata2=15.1.0
  - uriparser=0.9.8
  - urllib3=2.3.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - wrapt=1.17.0
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-cursor=0.1.4
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xerces-c=3.2.4
  - xkeyboard-config=2.38
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.6.4
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - accelerate==1.6.0
      - albucore==0.0.23
      - albumentations==2.0.5
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - diffusers==0.33.1
      - diffvg==0.0.1
      - docstring-parser==0.16
      - eval-type-backport==0.2.2
      - fsspec==2025.3.2
      - huggingface-hub==0.30.2
      - hydra-core==1.3.2
      - jsonargparse==4.39.0
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - lightning==2.5.1
      - omegaconf==2.3.0
      - openai-whisper==20240930
      - opencv-python-headless==4.11.0.86
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - regex==2024.11.6
      - safetensors==0.5.3
      - segmentation-models-pytorch==0.5.0
      - simsimd==6.2.1
      - stringzilla==3.12.5
      - svgpathtools==1.6.1
      - svgwrite==1.4.3
      - sympy==1.13.1
      - tiktoken==0.9.0
      - timm==1.0.15
      - tokenizers==0.21.1
      - transformers==4.51.3
      - typeshed-client==2.7.0
      - typing-inspection==0.4.0
      - utm==0.8.1
