# Chunked Inference Configuration

# Patch size for inference [height, width]
# Patches of this size will be processed independently 
# and then reassembled to form the full output
patch_size: [256, 256]

# Patch margin [height, width]
# Margin of overlap between patches to avoid edge artifacts
# The effective stride will be (patch_size - 2*patch_margin)
patch_margin: [50, 50]

# Additional inference settings
use_tta: false  # Test-time augmentation
tta_merge_mode: "mean"  # How to merge TTA results (mean, max, etc.)