# Regression metrics configuration for distance map prediction
metrics:
  - name: "MeanAbsoluteError"
    params:
      num_outputs: 1
      reduction: "elementwise_mean"
  
  - name: "MeanSquaredError"
    params:
      num_outputs: 1
      reduction: "elementwise_mean"
  
  - name: "RootMeanSquaredError"
    params:
      num_outputs: 1
      reduction: "elementwise_mean" 