# ----------------------------------------
# Segmentation-metrics configuration
# ----------------------------------------

metrics:

  # Dice
  - alias: dice
    path: metrics.dice
    class: ThresholdedDiceMetric
    params:
      threshold: 0          # 0 splits neg/pos
      greater_is_road: false # neg < 0  -> road = 1
      eps: 1e-6
      multiclass: false
      zero_division: 1.0

  # IoU
  - alias: iou
    path: metrics.iou
    class: ThresholdedIoUMetric
    params:
      threshold: 0
      greater_is_road: false
      eps: 1e-6
      multiclass: false     
      zero_division: 1.0

  # Connected-components quality
  - alias: ccq
    path: metrics.ccq
    class: ConnectedComponentsQuality
    params:
      min_size: 5
      tolerance: 2           # centroid distance in px
      threshold: 0
      greater_is_road: false
      data_dim: 2 # 2D data

  # APLS
  - alias: apls
    path: metrics.apls
    class: APLS
    params:
      threshold: 0
      greater_is_road: false
      angle_range: [135, 225]
      max_nodes: 1000
      max_snap_dist: 25
      allow_renaming: true
      min_path_length: 15
      data_dim: 2 # 2D data

# How often to compute each metric
train_frequencies:   {dice: 1,  iou: 1,  ccq: 20, apls: 50}
val_frequencies:     {dice: 1,  iou: 1,  ccq: 10,  apls: 10}
