# Segmentation Metrics Configuration

# List of metrics to evaluate
metrics:
  # # Dice coefficient
  # - alias: "dice"  # Shorthand name for the metric
  #   path: "torchmetrics.classification"
  #   class: "Dice"
  #   params:
  #     threshold: 0
  #     zero_division: 1.0

  # # IoU (Jaccard index)
  # - alias: "iou"
  #   path: "torchmetrics.classification"
  #   class: "JaccardIndex"
  #   params:
  #     task: "binary"
  #     threshold: 0
  #     num_classes: 2  # Binary segmentation

  # Dice
  - alias: "dice"  # Shorthand name for the metric
    path: "metrics.dice"
    class: "ThresholdedDiceMetric"
    params:
      threshold: 0
      eps: 1e-6
      multiclass: false
      zero_division: 1.0

  # IoU (Jaccard index)
  - alias: "iou"
    path: "metrics.iou"
    class: "ThresholdedIoUMetric"
    params:
      threshold: 0
      eps: 1e-6
      multiclass: true     # or false for single-class
      zero_division: 1.0

  # Connected Components Quality
  - alias: "ccq"
    path: "metrics.connected_components"
    class: "ConnectedComponentsQuality"
    params:
      min_size: 5
      tolerance: 2
      threshold: 0

  # Average Path Length Similarity
  - alias: "apls"
    path: "metrics.apls"
    class: "APLS"
    params:
      angle_range: [135, 225]
      max_nodes: 1000
      max_snap_dist: 25
      allow_renaming: true
      min_path_length: 10
      threshold: 0

# Per-metric frequencies for training - how often to compute each metric
train_frequencies:
  dice: 1    # Compute every epoch (lightweight metric)
  iou: 1     # Compute every epoch (lightweight metric)
  ccq: 1    # Compute every 10 epochs (moderately expensive)
  apls: 1   # Compute every 25 epochs (very computationally expensive)

# Per-metric frequencies for validation - how often to compute each metric
val_frequencies:
  dice: 1    # Compute every epoch
  iou: 1     # Compute every epoch
  ccq: 1     # Compute every 5 epochs
  apls: 1   # Compute every 10 epochs