# Segmentation Metrics Configuration

# List of metrics to evaluate
metrics:
  # Dice coefficient
  - alias: "dice"  # Shorthand name for the metric
    path: "torchmetrics.classification"
    class: "Dice"
    params:
      threshold: 0.5
      zero_division: 1.0

  # IoU (Jaccard index)
  - alias: "iou"
    path: "torchmetrics.classification"
    class: "JaccardIndex"
    params:
      task: "binary"
      threshold: 0.5
      num_classes: 2  # Binary segmentation

  # Connected Components Quality
  - alias: "ccq"
    path: "metrics.connected_components"
    class: "ConnectedComponentsQuality"
    params:
      min_size: 5
      tolerance: 2

  # Average Path Length Similarity
  - alias: "apls"
    path: "metrics.apls"
    class: "APLS"
    params:
      min_segment_length: 10
      max_nodes: 500
      sampling_ratio: 0.1

# Per-metric frequencies for training - how often to compute each metric
train_frequencies:
  dice: 1    # Compute every epoch (lightweight metric)
  iou: 1     # Compute every epoch (lightweight metric)
  ccq: 10    # Compute every 10 epochs (moderately expensive)
  apls: 25   # Compute every 25 epochs (very computationally expensive)

# Per-metric frequencies for validation - how often to compute each metric
val_frequencies:
  dice: 1    # Compute every epoch
  iou: 1     # Compute every epoch
  ccq: 5     # Compute every 5 epochs
  apls: 10   # Compute every 10 epochs