# TopoTokens Model Configuration

# Model path and class
path: "models.UNet_noRelu"  # Path to the module containing the model
class: "UNet"  # Name of the model class

# Model parameters
params:
  three_dimensional: False
  m_channels: 32
  n_convs: 2
  n_levels: 3
  dropout: 0.1
  batch_norm: True
  upsampling: "bilinear"
  pooling: "max"
  in_channels: 3
  out_channels: 1