# TopoTokens Model Configuration

# Model path and class
path: "models.custom_model"  # Path to the module containing the model
class: "TopoTokens"  # Name of the model class

# Model parameters
params:
  in_channels: 3  # RGB input
  out_channels: 1  # Binary segmentation output
  encoder_channels: 64  # Initial number of encoder channels
  decoder_channels: 32  # Initial number of decoder channels
  num_blocks: 4  # Number of encoder/decoder blocks
  dropout: 0.2  # Dropout rate