# Massachusetts Roads Dataset Configuration
seed: 42  # Random seed
split_cfg:
  seed: 42
  index_save_pth: "/cvlabdata2/cvlab/home/oner/Sinergia2/AL175-inds"
  # index_save_pth: "/home/ri/Desktop/Projects/Datasets/AL175-inds"
  sources:
    - type: "ratio"
      # path: "/home/ri/Desktop/Projects/Datasets/AL175"
      path: "/cvlabdata2/cvlab/home/oner/Sinergia2/AL175"
      layout: "flat"
      modalities:
        image:
          pattern: "^cube_(.*)\\.npy$"
        label:
          pattern: "^lbl_(.*)\\.npy$"
        distance:
          pattern: "^distlbl_(.*)\\.npy$"
      ratios:
        train: 0.75
        valid: 0.2
        test:  0.05

base_modalities: ["label", "image"]


# -----------------------------------------------------------------------------
# Dimensionality & Patch Extraction
# -----------------------------------------------------------------------------
data_dim: 3                # 2 = 2D patches, 3 = 3D volumes
patch_size: 96            # XY patch size
patch_size_z: 96           # Z-depth (only for 3D)
small_window_size: 8       # window for texture/variance check
validate_road_ratio: false # enforce minimum label coverage
threshold: 0.05            # minimum road fraction if above = true
# max_images: 10           # limit number of loaded images (null = no limit)
# max_images: null           # limit number of loaded images (null = no limit)
# max_attempts: 10           # retries to find a valid patch

# -----------------------------------------------------------------------------
# Computed Modalities
# -----------------------------------------------------------------------------
save_computed: true               # save new distance/SDF files
compute_again_modalities: false   # overwrite existing if true

distance_threshold: 15.0          # clip distance maps (null = no clip)
# sdf_iterations: 3                 # dilation iterations before SDF
# sdf_thresholds: [-7, 7]           # clip range for SDF values

# -----------------------------------------------------------------------------
# DataLoader Settings
# -----------------------------------------------------------------------------
train_batch_size: 32
val_batch_size: 1
test_batch_size: 1
num_workers: 4
pin_memory: true

# -----------------------------------------------------------------------------
# Augmentation
# -----------------------------------------------------------------------------
augmentation:
  flip_h: 
    prob: 0.5
  flip_v: 
    prob: 0.5
  flip_d: 
    prob: 0.5
  rotation:
    min: 0.0
    max: 360.0
    pad: false
  scale:
    min: 0.75
    max: 1.25
  # elastic:
  #   alpha_min: 1.0
  #   alpha_max: 2.0
  #   sigma_min: 4.0
  #   sigma_max: 8.0
  # brightness_contrast:
  #   alpha_min: 0.9
  #   alpha_max: 1.1
  #   beta_min: -10.0
  #   beta_max: 20.0
  # gamma:
  #   min: 0.8
  #   max: 1.2
  # gaussian_noise:
  #   min: 0.01
  #   max: 0.03
  # gaussian_blur:
  #   min: 0.5
  #   max: 1.5
  # bias_field:
  #   min: 0.2
  #   max: 0.4

# -----------------------------------------------------------------------------
# Normalization Settings
# -----------------------------------------------------------------------------

normalization:
  image:
    method: "divide_by"    
    threshold: 255      

  # image:
    # method: "zscore"     # options: minmax, zscore, robust, percentile, clip
    # eps: !!float 1e-8         # lower bound of your data range (or null to infer from image)

  distance: 
    method: "clip"     # no extra parameters
    min_val: 0
    max_val: 15

  # # 3) Robust normalization: clip to [lower_q, upper_q] quantiles, then min–max to [0,1]
  sdf:
    method: "clip"
    min_val: -7    
    max_val: 7  

  # label:
  #   method: "binarize"
  #   threshold: 127
  #   greater_is_road: True
  #   return_bool: true

order_ops: ["crop", "norm", "aug"]   # crop → normalise → augment 
# order_ops: ["norm", "aug", "crop"] # old behaviour
# order_ops: ["aug", "crop", "norm"] # yes, that works too


# -----------------------------------------------------------------------------
# Miscellaneous
# -----------------------------------------------------------------------------
verbose: false
