# Massachusetts Roads Dataset Configuration

# Dataset root directory
root_dir: "/home/ri/Desktop/Projects/Datasets/Mass_Roads/dataset"
# root_dir: "/cvlabdata2/cvlab/home/oner/Elyar/datasets/dataset"

# data_dim: 3,
# patch_size_z: 90,

# Batch sizes
train_batch_size: 64
val_batch_size: 1  # Usually 1 for full-image validation
test_batch_size: 1  # Usually 1 for full-image testing

# Patch and crop settings
patch_size: 512  # Size of training patches
small_window_size: 8  # Size of window to check for variation
validate_road_ratio: false  # Validate patch has enough road content
threshold: 0.05  # Minimum road ratio threshold

# Data loading settings
num_workers: 4
pin_memory: true

# Modality settings
split_cfg:
  mode: "folder"
  # for ratio-based splitting:
  # ratios:
  #   train: 0.7
  #   valid: 0.15
  #   test: 0.15

  # if you have flat folder structure instead:
  # ratio_folders:
  #   - path: "/path/to/flat/dataset"
  #     layout: "flat"
  #     modalities:
  #       image:
  #         pattern: ".*_sat\\.tif"
  #       label:
  #         pattern: ".*_map\\.png"

  source_folders:
    - path: "/home/ri/Desktop/Projects/Datasets/Mass_Roads/dataset"
      layout: "folders"
      modalities:
        image:
          folder: "sat"
        label:
          folder: "map"
        # distance:
          # folder: "distance"
        sdf:
          folder: "sdf"
      splits:
        train: "train"
        valid: "valid"
        test:  "test"

base_modality: "label"
# Distance transform settings
# distance_threshold: 20.0

# Signed distance function settings
sdf_iterations: 3
sdf_thresholds: [-7, 7]

# Augmentation settings
augmentations:
  - "flip_h"
  - "flip_v"
  - "rotation"

# Misc settings
# max_images: null  # No limit (set a number to limit images loaded)
max_images: 2 #640  # No limit (set a number to limit images loaded)
# max_attempts: 10  # Maximum attempts for finding valid patches
save_computed: true  # Save computed distance maps and SDFs
verbose: false  # Verbose output
seed: 42  # Random seed