# Massachusetts Roads Dataset Configuration
seed: 42  # Random seed
split_cfg:
  seed: 42
  index_save_pth: "/home/ri/Desktop/Projects/Datasets/Mass_Roads/inds"
  # index_save_pth: "/cvlabdata2/cvlab/home/oner/Elyar/datasets/mass-inds"
  sources:
    - type: "folder"
      path: "/home/ri/Desktop/Projects/Datasets/Mass_Roads/dataset"
      # path: "/cvlabdata2/cvlab/home/oner/Elyar/datasets/dataset"
      layout: "folders"
      modalities:
        image:
          folder: "sat"
        label:
          folder: "label"
        # distance:
          # folder: "distance"
        sdf:
          folder: "sdf"
      splits:
        train: "train"
        valid: "valid"
        test:  "test"

base_modalities: ["label", "image"]



# -----------------------------------------------------------------------------
# Dimensionality & Patch Extraction
# -----------------------------------------------------------------------------
data_dim: 2                # 2 = 2D patches, 3 = 3D volumes
patch_size: [512, 512]            
max_images: 10           # limit number of loaded images (null = no limit)
# max_images: null           # limit number of loaded images (null = no limit)
# max_attempts: 10           # retries to find a valid patch

# -----------------------------------------------------------------------------
# Computed Modalities
# -----------------------------------------------------------------------------
save_computed: true               # save new distance/SDF files
compute_again_modalities: false   # overwrite existing if true

sdf_iterations: 3                 # dilation iterations before SDF

# -----------------------------------------------------------------------------
# DataLoader Settings
# -----------------------------------------------------------------------------
train_batch_size: 2
val_batch_size: 1
test_batch_size: 1
num_workers: 4
pin_memory: true

# -----------------------------------------------------------------------------
# Augmentation
# -----------------------------------------------------------------------------
augmentation:
  # ------ Geometry (mirrors, rotations, scales, shifts) ------
  - name: flip_horizontal         # left-right mirror in X
    p: 0.8                        # 50 % chance
    modalities: ["image", "label", "distance", "sdf"]

  - name: flip_vertical           # top-bottom mirror in Y
    p: 0.8
    modalities: ["image", "label", "distance", "sdf"]

  # 3-D users can uncomment this for Z-axis mirroring.
  # - name: flip_depth
  #   p: 0.8
  #   modalities: ["image", "label", "distance", "sdf"]

  - name: rotation
    params:
      degrees: [0, 360]          # inclusive range (°)
    p: 0.8
    modalities: ["image", "label", "distance", "sdf"]

  - name: scaling
    params:
      scale_limit: [0.7, 1.8]     # isotropic zoom ∈ [0.9, 1.1]
    p: 0.8
    modalities: ["image", "label", "distance", "sdf"]

  # - name: translation
  #   params:
  #     shift_limit: [-0.01, 0.01]    # fractional shift of image size
  #   p: 0.8
  #   modalities: ["image", "label", "distance", "sdf"]

  # - name: elastic_deformation
  #   params:
  #     alpha: [5, 10]             # displacement intensity
  #     sigma: [10, 15]               # smoothing of displacement
  #   p: 0.8
  #   modalities: ["image", "label", "distance", "sdf"]

  # ---------------- Intensity-only (images only) -------------
  - name: brightness
    params:
      limit: [-0.2, 0.2]          # factor sampled → brightness=(1+Δ)
    p: 0.8
    modalities: ["image"]

  - name: contrast
    params:
      limit: [-0.2, 0.2]          # factor sampled similarly
    p: 0.8
    modalities: ["image"]

  - name: gamma
    params:
      gamma_limit: [0.8, 1.2]     # γ correction range
    p: 0.8
    modalities: ["image"]

  - name: gaussian_noise
    params:
      std: [0.0, 0.01]            # σ of additive Gaussian noise
      mean: 0                     # μ (keep at 0 for white noise)
    p: 0.8
    modalities: ["image"]

  - name: blur            # Gaussian blur with random odd kernel
    params:
      sigma: [0, 0.1]
      kernel_size: [3, 9] # random odd integer ∈ {3,5,7,9}
    p: 0.8
    modalities: ["image"]

  - name: color_jitter
    params:
      brightness: [0.1, 0.3]  # factor sampled uniformly in this range
      contrast:   [0.4, 0.6]  # likewise; gives wider/stronger jitter
      saturation: [-0.2,0.2]         # scalar still OK → symmetric ±20 %
      hue:        [-0.1, 0.1] # explicit low/high for hue shift (rad)
    p: 0.8
    modalities: ["image"]

# -----------------------------------------------------------------------------
# Normalization Settings
# -----------------------------------------------------------------------------

normalization:
  image:
    method: "divide_by"    
    threshold: 255      

  # image:
    # method: "zscore"     # options: minmax, zscore, robust, percentile, clip
    # eps: !!float 1e-8         # lower bound of your data range (or null to infer from image)

  distance: 
    method: "clip"     # no extra parameters
    min_val: 0
    max_val: 15

  # # 3) Robust normalization: clip to [lower_q, upper_q] quantiles, then min–max to [0,1]
  sdf:
    method: "clip"
    min_val: -7    
    max_val: 7  

  label:
    method: "boolean"
  
  # label:
  #   method: "binarize"
  #   threshold: 127
  #   greater_is_road: True
  #   return_bool: true

order_ops: ["norm", "aug"]   # normalise → augment 


# -----------------------------------------------------------------------------
# Miscellaneous
# -----------------------------------------------------------------------------
verbose: true
