callbacks:
  # Save best checkpoints per metric
  - name: BestMetricCheckpoint
    params:
      # relative to output_dir/
      dirpath: checkpoints
      # must match your metric loader
      metric_names:
        - dice
        - iou
        - ccq
        - apls
      mode: max               # or "min" (or a dict per metric)
      save_last: true
      last_k: 1
      filename_template: best_{metric}

  # Periodic full checkpoints (e.g. every 5 epochs)
  - name: PeriodicCheckpoint
    params:
      dirpath: backup_checkpoints
      every_n_epochs: 1
      prefix: epoch

  # 2D sample plots in TensorBoard
  - name: SamplePlotCallback
    params:
      num_samples: 5
      cmap: coolwarm

  # Save raw prediction .npy files
  - name: PredictionSaver
    # other timing controlled globally via load_callbacks args
    params:
      save_dir: saved_predictions

  # # Save PNG visualizations of preds vs GT
  # - name: PredictionLogger
  #   params:
  #     log_dir: prediction_logs
  #     log_every_n_epochs: 1
  #     max_samples: 4
  #     cmap: coolwarm

  # Archive configs & source at start (skipped when resuming)
  - name: ConfigArchiver
    params:
      output_dir: code
      # project_root provided to load_callbacks

  # Skip validation until epoch N
  - name: SkipValidation

  # Log learning-rate schedule to TensorBoard
  - name: LearningRateMonitor
    params:
      logging_interval: epoch
