# Main configuration for regression training (distance map prediction)
defaults:
  - dataset: drive_regression
  - model: baseline
  - loss: mse_loss
  - metrics: regression_metrics
  - inference: chunk
  - callbacks: callbacks_2d_simple

# Training settings
trainer:
  max_epochs: 10
  val_check_interval: 2.0
  log_every_n_steps: 50
  accelerator: "auto"
  devices: "auto"
  precision: 16

# Model settings
model:
  in_channels: 3  # RGB images
  out_channels: 1  # Single channel for distance map regression
  features: [64, 128, 256, 512]
  activation: "relu"
  dropout: 0.1

# Loss settings
loss:
  name: "MSELoss"
  params: {}

# Metrics settings
metrics:
  - name: "MeanAbsoluteError"
    params: {}
  - name: "MeanSquaredError"
    params: {}
  - name: "RootMeanSquaredError"
    params: {}

# Logging
logger:
  name: "tensorboard"
  log_model: true

# Checkpointing
checkpoint:
  dirpath: "checkpoints_regression"
  filename: "best_regression"
  monitor: "val_loss"
  mode: "min"
  save_top_k: 3 