# ----------------------------------------
# Segmentation-metrics configuration
# ----------------------------------------

metrics:

  # Dice
  - alias: dice
    path: metrics.dice
    class: ThresholdedDiceMetric
    params:
      threshold: 2          # 0 splits neg/pos
      greater_is_road: false # neg < 0  -> road = 1
      eps: 1e-6
      multiclass: false
      zero_division: 1.0
      data_dim: 3 # 2D data

  # IoU
  - alias: iou
    path: metrics.iou
    class: ThresholdedIoUMetric
    params:
      threshold: 2
      greater_is_road: false
      eps: 1e-6
      multiclass: false     
      zero_division: 1.0
      data_dim: 3 # 2D data

  # Connected-components quality
  - alias: ccq
    path: metrics.ccq
    class: ThresholdedCCQMetric
    params:
      slack: 3
      threshold: 2
      greater_is_road: false
      data_dim: 3 # 2D data

# How often to compute each metric
train_frequencies:   {dice: 1,  iou: 1,  ccq: 1}
val_frequencies:     {dice: 1,  iou: 1,  ccq: 1}
